name = "vecfun"
version = "0.1.0"
license = "MIT"
author = "Andre Smit"
maintainer = "freevryheid@gmail.com"
copyright = "Copyright 2022, Andre Smit"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }
[install]
library = false
